### ISSUE TITLE
resultaten vanuit statische data (google drive) zijn niet hetzelfde

### ISSUE THREAD

**Issue by valdemetriades** [ArtesiaWater/UGW#3]
Indien we gebruik maken van de statische data en de scripts runnen, krijgen we niet dezelfde resultaten:
- er zijn meer plekken waar helemaal geen DRN/RIV data in het model wordt gezet (géén peil en/of bodemhoogte bekend)
- de verdeling DRN/RIV lijkt anders (bv. HDSR gebied komt er helemaal niet in RIV)

Actie: scripts opnieuw draaien met de statische data en achterhalen waar eventueel een technische mismatch door komt.

Hierbij de resultaten die wij krijgen vanuit de statische data (Google Drive):
![BC_no_bottom_levels](https://user-images.githubusercontent.com/57270840/141755898-d5a2ef57-cddd-4307-8da3-b88cdeff4d61.png)
![BC_no_waterlevel-areas](https://user-images.githubusercontent.com/57270840/141755909-99f4b46f-ac79-4f51-998f-6c84ab5f5585.png)
![BC_types_in_gwmodel](https://user-images.githubusercontent.com/57270840/141755915-9909f62d-7eb0-45c4-b028-a169f89a4437.png)
![BC_types_in_source_data](https://user-images.githubusercontent.com/57270840/141755927-81c523c2-2eff-4b09-987e-76a859a8f720.png)

**Comment by dbrakenhoff** [comment]
The data I'm reading in now only has `SUB == 1` in the red areas. So that's the causing the difference in the final result. 

![image](https://user-images.githubusercontent.com/6552225/141817433-32eaddd2-9877-4560-84f6-585db63142dd.png)

So we'll have to figure out why this attribute has changed in the `water_areas.shp` file. So @d2hydro, any chance you can take a look at that one :)?

**Comment by d2hydro** [comment]
@dbrakenhoff, can you check if you get the correct results with this waterareas.shp: https://we.tl/t-fo27TgO9XL.

See here the sub on the google drive:
![image](https://user-images.githubusercontent.com/43996424/142839776-af0852b4-6eac-4ff6-bf62-15bcac8f4aca.png)

And here the sub in the file on the wetransfer:

![image](https://user-images.githubusercontent.com/43996424/142839910-2d9eb783-2f21-474a-bd91-17ccc1ba11e1.png)

I've send this last file via e-mail 18-03-2021. That corresponds with the date on the files and not with the date of the files in google drive.

**Comment by dbrakenhoff** [comment]
Thanks, that should take care of it.

**Comment by dbrakenhoff** [comment]
Data on Google Drive has been updated. Now the files reproduce the figures presented in the report. 
For download, [see here](https://drive.google.com/file/d/1unBNbwnTNGpkstSNV3TbaClQoieoP7e0/view?usp=sharing).

Closing issue.
